// Generated by CoffeeScript 1.6.3
(function() {
  var User;

  User = require("../models/user");

  exports.users = function(req, res) {
    return User.find().sort("name").exec(function(err, users) {
      return res.send(users);
    });
  };

}).call(this);
